# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'My English' do

pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
pod 'RxCocoa’, :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'

end

# Pods for My English

target 'My EnglishTests' do
    inherit! :search_paths
    
end
